
POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "Video node",
  "description": "Esse é o primeiroo vídeo",
  "duration": 184
}

###

GET http://localhost:3333/videos?search=node

###

PUT http://localhost:3333/videos/a0196af3-ad4f-4852-97be-482d5c3957da
Content-Type: application/json

{
  "title": "video 001",
  "description": "Esse é o primeiro vídeo",
  "duration": 188
}

###

DELETE http://localhost:3333/videos/191f617a-1961-465c-9cef-4c6ab4f5ae24